#pragma once

#pragma region CONTRA


#define CONTRA_ANI_IDLE_RIGHT 10000
#define CONTRA_ANI_IDLE_LEFT CONTRA_ANI_IDLE_RIGHT+1

#define CONTRA_ANI_WALK_RIGHT 10100
#define CONTRA_ANI_WALK_LEFT CONTRA_ANI_WALK_RIGHT+1

#define CONTRA_ANI_JUMP_RIGHT 10400
#define CONTRA_ANI_JUMP_LEFT CONTRA_ANI_JUMP_RIGHT+1

#define CONTRA_ANI_FALL_RIGHT 10000
#define CONTRA_ANI_FALL_LEFT CONTRA_ANI_FALL_RIGHT+1

#define CONTRA_ANI_DIE_RIGHT 10990
#define CONTRA_ANI_DIE_LEFT CONTRA_ANI_DIE_RIGHT+1

#define CONTRA_ANI_SWIM_RIGHT 11100
#define CONTRA_ANI_SWIM_LEFT CONTRA_ANI_SWIM_RIGHT+1


#pragma endregion

#pragma region CONTRA_BULLET
#define	CONTRA_BULLET_ANI_BASE_RIGHT 1099001
#define	CONTRA_BULLET_ANI_BASE_LEFT	CONTRA_BULLET_ANI_BASE_RIGHT+1
#pragma endregion

#pragma region INFARY
#define	INFARY_ANI_WALK_RIGHT 20100
#define	INFARY_ANI_WALK_LEFT INFARY_ANI_WALK_RIGHT+1

#define	INFARY_ANI_AIM_RIGHT 20010
#define	INFARY_ANI_AIM_LEFT	INFARY_ANI_AIM_RIGHT+1

#define INFARY_ANI_SHOOT_RIGHT	20110
#define	INFARY_ANI_SHOOT_LEFT	INFARY_ANI_SHOOT_RIGHT+1

#define INFARY_ANI_JUMP_RIGHT 20990
#define INFARY_ANI_JUMP_LEFT INFARY_ANI_JUMP_RIGHT+1

#define INFARY_ANI_DIE_RIGHT 20990
#define INFARY_ANI_DIE_LEFT INFARY_ANI_DIE_RIGHT+1
#pragma endregion

#pragma region SNIPER
#define	SNIPER_ANI_AIM_RIGHT 40010
#define	SNIPER_ANI_AIM_LEFT	SNIPER_ANI_AIM_RIGHT+1

#define SNIPER_ANI_AIM_UP_RIGHT 40030
#define SNIPER_ANI_AIM_UP_LEFT SNIPER_ANI_AIM_UP_RIGHT+1

#define SNIPER_ANI_AIM_DOWN_RIGHT 40020
#define SNIPER_ANI_AIM_DOWN_LEFT SNIPER_ANI_AIM_DOWN_RIGHT+1

#define	SNIPER_ANI_SHOOT_RIGHT 40110
#define	SNIPER_ANI_SHOOT_LEFT	SNIPER_ANI_SHOOT_RIGHT+1

#define SNIPER_ANI_SHOOT_UP_RIGHT 40130
#define SNIPER_ANI_SHOOT_UP_LEFT SNIPER_ANI_SHOOT_UP_RIGHT+1

#define SNIPER_ANI_SHOOT_DOWN_RIGHT 40120
#define SNIPER_ANI_SHOOT_DOWN_LEFT SNIPER_ANI_SHOOT_DOWN_RIGHT+1

#define SNIPER_ANI_DIE_RIGHT 40990
#define SNIPER_ANI_DIE_LEFT SNIPER_ANI_DIE_RIGHT +1
#pragma endregion

