#include "Contra_GET_ANI.h"

int Get_CharANI_ID(int character, int behavior)
{
	unordered_map<int, int> arr;

	switch (character)
	{
	case CHAR_CONTRA:
	{
		arr[ACT_IDLE_LEFT] = CONTRA_ANI_IDLE_LEFT;
		arr[ACT_IDLE_RIGHT] = CONTRA_ANI_IDLE_RIGHT;
		arr[ACT_WALK_LEFT] = CONTRA_ANI_WALK_LEFT;
		arr[ACT_WALK_RIGHT] = CONTRA_ANI_WALK_RIGHT;
		arr[ACT_JUMP_LEFT] = CONTRA_ANI_JUMP_LEFT;
		arr[ACT_JUMP_RIGHT] = CONTRA_ANI_JUMP_RIGHT;
		arr[ACT_SWIM_LEFT] = CONTRA_ANI_SWIM_LEFT;
		arr[ACT_SWIM_RIGHT] = CONTRA_ANI_SWIM_RIGHT;
		arr[ACT_FALL_LEFT] = CONTRA_ANI_FALL_LEFT;
		arr[ACT_FALL_RIGHT] = CONTRA_ANI_FALL_RIGHT;
		arr[ACT_DIE_LEFT] = CONTRA_ANI_FALL_LEFT;
		arr[ACT_DIE_RIGHT] = CONTRA_ANI_FALL_RIGHT;
		break;
	}

	case RED_GUNNER:
	{
		arr[ACT_IDLE_LEFT] = INFARY_ANI_WALK_LEFT;
		arr[ACT_IDLE_RIGHT] = INFARY_ANI_WALK_RIGHT;
		arr[ACT_WALK_LEFT] = INFARY_ANI_WALK_LEFT;
		arr[ACT_WALK_RIGHT] = INFARY_ANI_WALK_RIGHT;
		arr[ACT_JUMP_LEFT] = INFARY_ANI_JUMP_LEFT;
		arr[ACT_JUMP_RIGHT] = INFARY_ANI_JUMP_RIGHT;
		arr[ACT_SWIM_LEFT] = INFARY_ANI_DIE_LEFT;
		arr[ACT_SWIM_RIGHT] = INFARY_ANI_DIE_RIGHT;
		arr[ACT_FALL_LEFT] = INFARY_ANI_JUMP_LEFT;
		arr[ACT_FALL_RIGHT] = INFARY_ANI_JUMP_RIGHT;
		arr[ACT_DIE_LEFT] = INFARY_ANI_DIE_LEFT;
		arr[ACT_DIE_RIGHT] = INFARY_ANI_DIE_RIGHT;
		break;
	}


	default:
		DebugOut(L"[ERROR] Character ID is undefined.\n");
		return -1;
	}

	return arr[behavior];
}