#pragma once


#define ANI_IDLE_RIGHT 10000
#define ANI_IDLE_LEFT ANI_IDLE_RIGHT+1

#define ANI_WALK_RIGHT 10100
#define ANI_WALK_LEFT ANI_WALK_RIGHT+1

#define ANI_JUMP_RIGHT 10400
#define ANI_JUMP_LEFT ANI_JUMP_RIGHT+1

#define ANI_FALL_RIGHT 10400
#define ANI_FALL_LEFT ANI_FALL_RIGHT+1

#define ANI_SWIM_RIGHT 11100
#define ANI_SWIM_LEFT ANI_SWIM_RIGHT+1
